<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ika_bot">

  <xacro:property name="body_len" value="1.2"/> 
  <xacro:property name="body_width" value="0.6"/>
  <xacro:property name="body_height" value="0.3"/> 
  <xacro:property name="ground_clearance" value="0.20"/>
  <xacro:property name="wheel_radius" value="0.25"/> 
  <xacro:property name="wheel_width" value="0.15"/>

  <xacro:macro name="box_inertia" params="m x y z">
    <inertial><mass value="${m}"/><inertia ixx="${(m/12)*(y*y+z*z)}" ixy="0" ixz="0" iyy="${(m/12)*(x*x+z*z)}" iyz="0" izz="${(m/12)*(x*x+y*y)}"/></inertial>
  </xacro:macro>
  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial><mass value="${m}"/><inertia ixx="${(m/12)*(3*r*r+h*h)}" ixy="0" ixz="0" iyy="${(m/12)*(3*r*r+h*h)}" iyz="0" izz="${(m/2)*(r*r)}"/></inertial>
  </xacro:macro>

  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed"><parent link="base_footprint"/><child link="base_link"/><origin xyz="0 0 ${ground_clearance + body_height/2}"/></joint>

  <link name="base_link">
    <visual><geometry><box size="${body_len} ${body_width} ${body_height}"/></geometry><material name="gray"><color rgba="0.5 0.5 0.5 1"/></material></visual>
    <collision><geometry><box size="${body_len} ${body_width} ${body_height}"/></geometry></collision>
    <xacro:box_inertia m="60.0" x="${body_len}" y="${body_width}" z="${body_height}"/>
  </link>
  <gazebo reference="base_link"><material>Gazebo/Grey</material></gazebo>

  <xacro:macro name="wheel" params="prefix x_pos y_pos">
    <link name="${prefix}_wheel">
      <visual><geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry><material name="black"><color rgba="0 0 0 1"/></material><origin rpy="${pi/2} 0 0"/></visual>
      <collision><geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry><origin rpy="${pi/2} 0 0"/></collision>
      <xacro:cylinder_inertia m="10.0" r="${wheel_radius}" h="${wheel_width}"/>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/><child link="${prefix}_wheel"/>
      <origin xyz="${x_pos} ${y_pos} ${wheel_radius - (ground_clearance + body_height/2)}"/><axis xyz="0 1 0"/>
    </joint>
    <gazebo reference="${prefix}_wheel">
      <material>Gazebo/Black</material>
      <mu1 value="2.0"/> <mu2 value="0.1"/> <kp value="10000000.0"/> <kd value="1.0"/>
      <fdir1 value="1 0 0"/> 
    </gazebo>
  </xacro:macro>

  <xacro:wheel prefix="rear_left" x_pos="-0.55" y_pos="0.45"/>
  <xacro:wheel prefix="rear_right" x_pos="-0.55" y_pos="-0.45"/>
  <xacro:wheel prefix="front_left" x_pos="0.55" y_pos="0.45"/>
  <xacro:wheel prefix="front_right" x_pos="0.55" y_pos="-0.45"/>

  <link name="gimbal_base">
    <visual><geometry><cylinder radius="0.2" length="0.1"/></geometry><material name="black"/></visual>
    <collision><geometry><cylinder radius="0.2" length="0.1"/></geometry></collision>
    <xacro:cylinder_inertia m="2.0" r="0.2" h="0.1"/>
  </link>
  <joint name="gimbal_base_joint" type="fixed"><parent link="base_link"/><child link="gimbal_base"/><origin xyz="0.4 0 ${body_height/2 + 0.05}"/></joint>

  <link name="gimbal_yaw_link">
    <visual><geometry><box size="0.15 0.15 0.2"/></geometry><material name="blue"/></visual>
    <xacro:box_inertia m="0.5" x="0.15" y="0.15" z="0.2"/>
  </link>
  <joint name="gimbal_yaw_joint" type="revolute">
    <parent link="gimbal_base"/><child link="gimbal_yaw_link"/><axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="500" velocity="2.0"/><origin xyz="0 0 0.1"/>
  </joint>

  <link name="gimbal_pitch_link">
    <visual><geometry><box size="0.2 0.1 0.1"/></geometry><material name="red"/></visual>
    <xacro:box_inertia m="0.5" x="0.2" y="0.1" z="0.1"/>
  </link>
  <joint name="gimbal_pitch_joint" type="revolute">
    <parent link="gimbal_yaw_link"/><child link="gimbal_pitch_link"/><axis xyz="0 1 0"/>
    <limit lower="-0.5" upper="0.5" effort="500" velocity="2.0"/><origin xyz="0 0 0.15"/>
  </joint>

  <link name="camera_link"><visual><geometry><box size="0.08 0.15 0.08"/></geometry><material name="black"/></visual></link>
  <joint name="camera_joint" type="fixed"><parent link="gimbal_pitch_link"/><child link="camera_link"/><origin xyz="0.1 0 0"/></joint>
  
  <link name="camera_link_optical"/>
  <joint name="camera_optical_joint" type="fixed"><parent link="camera_link"/><child link="camera_link_optical"/><origin rpy="${-pi/2} 0 ${-pi/2}"/></joint>

  <link name="laser_frame"><visual><geometry><cylinder radius="0.08" length="0.08"/></geometry><material name="blue"/></visual></link>
  <joint name="laser_joint" type="fixed"><parent link="base_link"/><child link="laser_frame"/><origin xyz="0 0 ${body_height/2 + 0.08}"/></joint>

  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros><namespace>/</namespace><remapping>~/out:=joint_states</remapping></ros>
      <update_rate>50</update_rate>
      <joint_name>front_left_wheel_joint</joint_name>
      <joint_name>front_right_wheel_joint</joint_name>
      <joint_name>rear_left_wheel_joint</joint_name>
      <joint_name>rear_right_wheel_joint</joint_name>
      <joint_name>gimbal_yaw_joint</joint_name>
      <joint_name>gimbal_pitch_joint</joint_name>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros><namespace>/</namespace></ros>
      
      <num_wheel_pairs>2</num_wheel_pairs>
      <left_joint>front_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      
      <wheel_separation>1.1</wheel_separation>
      <wheel_diameter>0.5</wheel_diameter>
      <max_wheel_torque>50000.0</max_wheel_torque>
      <max_wheel_acceleration>20.0</max_wheel_acceleration>
      
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf> 
      <publish_wheel_tf>true</publish_wheel_tf> 
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_footprint</robot_base_frame>
    </plugin>
  </gazebo>

  <ros2_control name="GazeboSystem" type="system">
    <hardware><plugin>gazebo_ros2_control/GazeboSystem</plugin></hardware>
    <joint name="gimbal_yaw_joint"><command_interface name="position"/><state_interface name="position"/></joint>
    <joint name="gimbal_pitch_joint"><command_interface name="position"/><state_interface name="position"/></joint>
  </ros2_control>
  
  <gazebo><plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so"><parameters>$(find ika_bot_description)/config/gimbal_controllers.yaml</parameters></plugin></gazebo>

  <gazebo reference="camera_link">
    <sensor name="camera_sensor" type="camera">
      <visualize>true</visualize><update_rate>30.0</update_rate>
      <camera><horizontal_fov>1.5</horizontal_fov><image><width>640</width><height>480</height><format>R8G8B8</format></image><clip><near>0.05</near><far>20.0</far></clip></camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so"><frame_name>camera_link_optical</frame_name></plugin>
    </sensor>
  </gazebo>

  <gazebo reference="laser_frame">
    <sensor name="lidar" type="ray">
      <visualize>false</visualize><update_rate>10</update_rate>
      <ray><scan><horizontal><samples>360</samples><resolution>1</resolution><min_angle>-3.14</min_angle><max_angle>3.14</max_angle></horizontal></scan><range><min>1.0</min><max>20.0</max></range></ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so"><ros><argument>~/out:=scan</argument></ros><output_type>sensor_msgs/LaserScan</output_type><frame_name>laser_frame</frame_name></plugin>
    </sensor>
  </gazebo>
</robot>